src/members/urls.py
from django.urls import path
from . import views

app_name='members'
urlpatterns = [
    path('login_user/', views.login_user, name="login"),
    path('register_user/', views.register_user, name="register_user"),
    path('logout_user/', views.logout_user, name="logout_user"),
]

src/orgvote/urls.py
from django.urls import path
from . import views
from .views import QuestionCreateView, TopicCreateView, SurveyCreateView, OrganizationCreateView, SurveyDetailView, QuestionDetailView, TopicDetailView, OrganizationDetailView, vote, HomePageView, OrganizationListView

# define the urls that will be used under the orgvote/ domain
app_name = "orgvote"
urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("organizations/", OrganizationListView.as_view(), name="Organizations"),
    path("create-question/", QuestionCreateView.as_view(), name="createQuestion"),
    path("create-topic/", TopicCreateView.as_view(), name="createTopic"),
    path("create-survey/", SurveyCreateView.as_view(), name="createSurvey"),
    path("create-organization/", OrganizationCreateView.as_view(), name="createOrganization"),
    path("survey-details<int:id>/", SurveyDetailView.as_view(), name="surveyView"),
    # path("question-details<int:id>/", QuestionDetailView.as_view(), name="questionView"),
    path("topic-details<int:id>/", TopicDetailView.as_view(), name="topicView"),
    path("organization-details<int:id>/", OrganizationDetailView.as_view(), name="organizationView"),
    path("question-vote<question_id>/", vote, name='questionVote')
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # adding the voting_system/urls.py file so that we don't have to add every subdomain of voting_system/ to this file
    path('orgvote/', include('orgvote.urls')),
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('members/', include('django.contrib.auth.urls'))

]

src/survey/urls.py
from django.urls import path
from . import views

# define the urls that will be used under the voting_system/ domain
urlpatterns = [
    path("", views.index, name="index"),
]

src/orgvote/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect

# Create your models here.

class Organization(models.Model):
    name = models.CharField(max_length=50)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null = True)
    
    pub_time = models.DateTimeField(auto_now_add=True, null = True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("orgvote:Organizations")

class Topic(models.Model):
    name = models.CharField(max_length=50)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    pub_time = models.DateTimeField(auto_now_add=True, null = True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("orgvote:home")

class Survey(models.Model):
    name = models.CharField(max_length=50) 
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    pub_time = models.DateTimeField(auto_now_add=True, null = True)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("orgvote:home")

class Question(models.Model):
    name = models.CharField(max_length=50, default="question")
    pub_time = models.DateTimeField(auto_now_add=True, null = True)

    question_text = models.TextField() 
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)

    choice1 = models.CharField(max_length=50)
    choice1_votes = models.IntegerField(default=0)

    choice2 = models.CharField(max_length=50)
    choice2_votes = models.IntegerField(default=0)

    choice3 = models.CharField(max_length=50)
    choice3_votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("orgvote:home")


# class Choice(models.Model):
#     choice_text= models.CharField() 
#     question = models.ForeignKey(Organization, on_delete=models.CASCADE)
#     votes = models.IntegerField(default=0)

src/orgvote/forms.py
from django import forms

from .models import Question, Topic, Survey, Organization

class QuestionModelForm(forms.ModelForm):
    class Meta:
        model = Question
        fields =[
            'name',
            'question_text',
            'survey',
            'choice1',
            'choice2',
            'choice3',
        ]

class TopicModelForm(forms.ModelForm):
    class Meta:
        model = Topic 
        fields =[
           'name',
           'organization' 
        ]

class SurveyModelForm(forms.ModelForm):
    class Meta:
        model = Survey
        fields =[
            'name',
            'topic' 
        ]

class OrganizationModelForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields =[
            'name'
        ]

src/orgvote/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, CreateView, DetailView, TemplateView
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import QuestionModelForm, TopicModelForm, SurveyModelForm, OrganizationModelForm
from .models import Question, Topic, Survey, Organization 

# Create your views here.
def index(request):
    return HttpResponse("Hello World. this is the orgvote app")

class HomePageView(TemplateView):
    template_name = 'orgvote/home.html'

class OrganizationListView(LoginRequiredMixin,ListView):
    model = Organization
    template_name = "orgvote/organizations.html"
    

class QuestionCreateView(LoginRequiredMixin,CreateView):
    template_name = "orgvote/create.html"
    form_class = QuestionModelForm
    queryset = Question.objects.all()

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            new_question = Question.objects.latest("pub_time")
            survey_id= new_question.survey.id
            return HttpResponseRedirect(reverse('orgvote:surveyView', kwargs={'id': survey_id}))

        return render(request, self.template_name, {"form": form})

class TopicCreateView(LoginRequiredMixin,CreateView):
    template_name = "orgvote/create.html"
    form_class = TopicModelForm
    queryset = Topic.objects.all()

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            new_topic = Topic.objects.latest("pub_time")
            org_id = new_topic.organization.id
            return HttpResponseRedirect(reverse('orgvote:organizationView', kwargs={'id': org_id}))

        return render(request, self.template_name, {"form": form})
    
class SurveyCreateView(LoginRequiredMixin, CreateView):
    template_name = "orgvote/create.html"
    form_class = SurveyModelForm
    queryset = Survey.objects.all()

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            new_survey = Survey.objects.latest("pub_time")
            topic_id = new_survey.topic.id
            return HttpResponseRedirect(reverse('orgvote:topicView', kwargs={'id': topic_id}))

        return render(request, self.template_name, {"form": form})

class OrganizationCreateView(LoginRequiredMixin, CreateView):
    template_name = "orgvote/create.html"
    form_class = OrganizationModelForm
    queryset = Organization.objects.all()

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            organization = form.save(commit=False)
            organization.created_by = request.user
            organization.save()
            return HttpResponseRedirect(reverse('orgvote:Organizations'))
        return render(request, self.template_name, {"form": form})


class SurveyDetailView(LoginRequiredMixin,DetailView):
    template_name = "orgvote/survey-details.html"
    queryset = Survey.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Survey, id = id_) 

class TopicDetailView(LoginRequiredMixin,DetailView):
    template_name = "orgvote/topic-details.html"
    queryset = Topic.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Topic, id = id_) 

class OrganizationDetailView(LoginRequiredMixin,DetailView):
    template_name = "orgvote/organization-details.html"
    queryset = Organization.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Organization, id = id_) 

class QuestionDetailView(LoginRequiredMixin,DetailView):
    template_name = "orgvote/question-details.html" 

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Question, id = id_) 

# inspired by code from https://github.com/PrettyPrinted/youtube_video_code.git
def vote(request, question_id):
    question = Question.objects.get(pk=question_id)
    survey_id = question.survey.id
    if request.method == 'POST':

        selected_option = request.POST['question']
        if selected_option == 'choice1':
            question.choice1_votes+= 1
        elif selected_option == 'choice2':
            question.choice2_votes+= 1
        elif selected_option == 'choice3':
            question.choice3_votes+= 1
        else:
            return HttpResponse(400, 'Invalid form')

        question.save()

        return HttpResponseRedirect(reverse('orgvote:surveyView', kwargs={'id': survey_id}))

    context = {
        'question' : question
    }
    return render(request, 'orgvote/question-vote.html', context)

src/orgvote/templates/orgvote/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Orgvote</title>

        <meta name="Author" content="Butch For President">
        <link rel="stylesheet" href="{% static 'orgStyles.css' %}">
    </head>
    <body class="backgroundTime">
        <nav>
            <ul class="mainNavBar">
                <li class="navBar"><a href="{% url 'orgvote:home' %}">Home</a></li>
            </ul>
        </nav>

        <form action="." method="POST" id="creation">
            <input type="hidden" name="next" value="{{ request.path }}">
            {% csrf_token %}
            {{form.as_p}}
            <!-- <input id="finale" type ='submit' value="Save" onclick="history.back()"/> -->
                <button type="submit">Save</button>
        </form>

    </body>
</html>

src/orgvote/templates/orgvote/create_survey.html
<form action="." method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type ='submit' value="Save" />

</form>

src/orgvote/templates/orgvote/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Orgvote</title>

        <meta name="Author" content="Butch For President">
        <link rel="stylesheet" href="{% static 'orgStyles.css' %}">
    </head>
    <body class="backgroundTime">
        <nav>
            <ul class="mainNavBar">
                <li class="navBar"><a href="{% url 'orgvote:home' %}">Home</a></li>
            </ul>
        </nav>

        <ul class="listTime">
            <!-- Iterate over object_list -->
            {{survey.name}}
            {% for choice in survey.question_set.all%}
            <!-- Display Objects -->
            <li class="theFinePrint">{{ choice.name }}</li>
        
            <hr/>
            <!-- If object_list is empty  -->
            {% empty %}
            <li class="theFinePrint">No objects yet.</li>
            {% endfor %}
        </ul>

    </body>
</html>

src/orgvote/templates/orgvote/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Butch For President</title>

    <meta name="description" content="The Home page for Butch for President!">
    <meta name="Author" content="Bruno Sánchez">
    <meta property="og:title" content="Home | Butch for President">
    <meta property="og:type" content="website"> 

    <meta property="og:description" content="Butch for Presidnet - Home Page"> <!--For social media stuff this helps, but ignore for now-->
    <link rel="stylesheet" href="styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'orgStyles.css' %}">
    <!-- <i class="icon-list-ol"></i> icon-list-ol--> 
    <link rel="icon" href="images\2x\baseline_poll_black_24dp.png">
    <!--fontawesome.com is a place to get icons!-->
    
</head>
<body class="backgroundTime">
    <!--
        <nav>
            <ul class="mainNavbar">
                <li class="NavBar"><a>Home</a></li>
            </ul>
        </nav>
    -->
    

    <div class="titlePositioning">
        <div class="titleContent">
            <h1>Butch For President!</h1>
        </div>
    </div>
    <div class="boxTime">
        {% if user.is_authenticated %}
        <div id="indexBackgroundImage">
            <div class="logout">
                <h2 id="logoutButton" class="homeLogins centered"><a href="{% url 'members:logout_user' %}">Logout</a></h2> 
            </div>
        </div>
        
        {% else %}
        <div id="indexBackgroundImage">
            <div class="login">
                <h2 id="loginButton" class="homeLogins centered"><a href="{% url 'members:login' %}">Login</a></h2> 
            </div>
        </div>

        <div id="indexBackgroundImage">
            <div class="register">
                <h2 id="registerButton" class="homeLogins centered"><a href="{% url 'members:register_user' %}">Register</a></h2> <!--Here we'll view the list of organizations!-->
            </div>
        </div>
        {% endif %}

        {% if user.is_authenticated %}
        <div id="indexBackgroundImage">
            <div class="voteHere">
                <h2 id="voteHereButton" class="homeLogins centered"><a href="{% url 'orgvote:Organizations' %}">View Organizations!</a></h2> <!--Here we'll view the list of organizations!-->
            </div>
        </div>
        {% endif %}

    </div>
    <div class="indexMainText centered">
        <h2>
            Does your group have questions, but have a hard time answering them?
        </h2>
        <p id="indexCentered">
            Welcome to a questionaire voting system! <br><br>

            Organizations can create topics, surveys, and questions for their members to answer.<br>
            Their votes are stored in the database and are only visible to organization admins!<br><br>

            Feel free to log on and answer questions!<br><br>

            Please vote responsibly!
        </p>
    </div>
    
</body>
<footer>

</footer>
</html>

src/orgvote/templates/orgvote/organization-details.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Orgvote</title>

        <meta name="Author" content="Butch For President">
        <link rel="stylesheet" href="{% static 'orgStyles.css' %}">
    </head>
    <body class="backgroundTime">
        <nav>
            <ul class="mainNavBar">
                <li class="navBar"><a href="{% url 'orgvote:home' %}">Home</a></li>
            </ul>
        </nav>

        <ul class="listTime">
            <!-- Iterate over object_list -->
            {{organization.name}}
            {% for topic in organization.topic_set.all%}
            <!-- Display Objects -->
            <li class="listChoiceOption"><a href="{% url 'orgvote:topicView' topic.id %}">{{ topic.name }}</a></li>
        
            <hr/>
            <!-- If object_list is empty  -->
            {% empty %}
            <li>No objects yet.</li>
            {% endfor %}
        </ul>

        {% if user == organization.created_by %}
        <button type="button" class="buttonMove">
            <a href="{% url 'orgvote:createTopic' %}">Create Topic</a>
        </button>
        {% endif %}

    </body>
</html>

src/orgvote/templates/orgvote/organization-list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Orgvote</title>

        <meta name="Author" content="Butch For President">
        <link rel="stylesheet" href="{% static 'orgStyles.css' %}">
    </head>
    <body>
        <ul class="mainNavBar">
            <li class="navBar"><a href="{% url 'orgvote:home' %}">Home</a></li>
        </ul>
    </body>
</html>

src/orgvote/templates/orgvote/organizations.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Orgvote</title>

        <meta name="Author" content="Butch For President">
        <link rel="stylesheet" href="{% static 'orgStyles.css' %}">
    </head>
    <body class="backgroundTime">
        <nav>
            <ul class="mainNavBar">
                <li class="navBar"><a class="" href="{% url 'orgvote:home' %}">Home</a></li>
            </ul>
        </nav>
        
        <ul class="listTime">
            <!-- Iterate over object_list -->
            {% for organization in object_list %}
            <!-- Display Objects -->
            <li class="listChoiceOption">{{ organization.name }}</li>
            <li class="listChoiceOptionLink listChoiceOption"><a href="{% url 'orgvote:organizationView' organization.id %}">{{ "link" }}</a></li>
        
            <hr/>
            <!-- If object_list is empty  -->
            {% empty %}
            <li>No objects yet.</li>
            {% endfor %}
        </ul>
        <button type="button" class="buttonMove">
            <a href="{% url 'orgvote:createOrganization' %}">Create Organization</a>
        </button>

    </body>
</html>

src/orgvote/templates/orgvote/question-details.html
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Orgvote</title>

        <meta name="Author" content="Butch For President">
        <link rel="stylesheet" href="{% static 'orgStyles.css' %}">
    </head>
    <body class="backgroundTime">
        <nav>
            <ul class="mainNavBar">
                <li class="navBar"><a href="{% url 'orgvote:home' %}">Home</a></li>
            </ul>
        </nav>
        <ul class="listTime">
            <!-- Iterate over object_list -->
            {{question.name}}
            <!-- Display Objects -->

            <!-- Display Objects -->
            <li>{{ question.choice1 }}</li>
            <li class="listChoiceOptionLink">{{ question.choice1_votes}}</li>
            <li>{{ question.choice2 }}</li>
            <li class="listChoiceOptionLink">{{ question.choice2_votes}}</li>
            <li>{{ question.choice3 }}</li>
            <li class="listChoiceOptionLink">{{ question.choice3_votes}}</li>
        
            <hr/>
            <!-- If object_list is empty  -->
            
        </ul>
    </body>
</html>

src/orgvote/templates/orgvote/question-vote.html
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Orgvote</title>

        <meta name="Author" content="Butch For President">
        <link rel="stylesheet" href="{% static 'orgStyles.css' %}">
    </head>
    <body class="backgroundTime">
        <nav>
            <ul class="mainNavBar">
                <li class="navBar"><a href="{% url 'orgvote:home' %}">Home</a></li>
            </ul>
        </nav>
        <!-- inspried by code from https://github.com/PrettyPrinted/youtube_video_code.git-->
        <div class="row listTime">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Cast Your Vote</h3>
                    </div>

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <h2>{{ question.question_text}}</h2>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-12">
                                <hr />

                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <div class="radio">
                                            <label class="choiceOption">
                                                <input type="radio" name="question" value="choice1" required>
                                                {{ question.choice1 }}
                                            </label> &nbsp;
                                            <label class="choiceOption">
                                                <input type="radio" name="question" value="choice2">
                                                {{ question.choice2 }}
                                            </label> &nbsp;
                                            <label class="choiceOption">
                                                <input type="radio" name="question" value="choice3">
                                                {{ question.choice3 }}
                                            </label> &nbsp;
                                        </div>
                                    </div>
                                    
                                    <hr />

                                    <button type="submit" class="btn btn-info">
                                        Submit
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </body>
</html>

src/orgvote/templates/orgvote/survey-details.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Orgvote</title>

        <meta name="Author" content="Butch For President">
        <link rel="stylesheet" href="{% static 'orgStyles.css' %}">
    </head>
    <body class="backgroundTime">
        <nav>
            <ul class="mainNavBar">
                <li class="navBar"><a href="{% url 'orgvote:home' %}">Home</a></li>
            </ul>
        </nav>
        <ul class="listTime">
            <!-- Iterate over object_list -->
            {{survey.name}}
            {% for question in survey.question_set.all%}
            <!-- Display Objects -->
            <li class="listChoiceOption"><a href="{% url 'orgvote:questionVote' question.id %}">{{ question.name }}</a></li>
        
            <hr/>
            <!-- If object_list is empty  -->
            {% empty %}
            <li>No objects yet.</li>
            {% endfor %}
        </ul>
        {% if user == survey.topic.organization.created_by %}
        <button type="button" class="buttonMove">
            <a href="{% url 'orgvote:createQuestion' %}">Create Question</a>
        </button>
        {% endif %}
    </body>
</html>

src/orgvote/templates/orgvote/topic-details.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Orgvote</title>

        <meta name="Author" content="Butch For President">
        <link rel="stylesheet" href="{% static 'orgStyles.css' %}">
    </head>
    <body class="backgroundTime">
        <nav>
            <ul class="mainNavBar">
                <li class="navBar"><a href="{% url 'orgvote:home' %}">Home</a></li>
            </ul>
        </nav>
        <ul class="listTime">
            <!-- Iterate over object_list -->
            {{topic.name}}
            {% for survey in topic.survey_set.all%}
            <!-- Display Objects -->
            <li class="listChoiceOption"><a href="{% url 'orgvote:surveyView' survey.id %}">{{ survey.name }}</a></li>
        
            <hr/>
            <!-- If object_list is empty  -->
            {% empty %}
            <li>No objects yet.</li>
            {% endfor %}
        </ul>
        {% if user == topic.organization.created_by %}
        <button type="button" class="buttonMove">
            <a href="{% url 'orgvote:createSurvey' %}">Create Survey</a>
        </button>
        {% endif %}
    </body>
</html> 